## Numpy

In [1]:
import numpy as np

In [6]:
## create array using numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 columns


array([[1, 2, 3, 4, 5]])

In [14]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [19]:
print(np.arange(0,10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
## Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## element wise addition
print("Addition: ", arr1 + arr2)
print("Subtraction: ", arr1 - arr2)
print("Multiplication: ", arr1 * arr2)
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [35]:
## universal functions
arr = np.array([1,2,3,4,10])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 2.30258509]


In [38]:
## array slicing and indexing
arr = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
print(arr)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
